### PR TITLE
Sync with upstream, add Drupal

### PR DESCRIPTION
**Pull request by seemk**
Most relevant changes, but not all of them:

* From upstream: integrations are now properly sandboxed, so when an error happens in the instrumentation's PHP code it won't cause errors in the application - instead the span will have partial information. This changed the integration API, introducing `SpanData` class which is created on the native side and removing `dd_trace_forward_call`.

* From upstream: each PHP major version now has its own native extension code (`ext/php*`), for example https://github.com/seemk/signalfx-php-tracing/tree/dd-sync-pr/ext/php7. Renamed the extensions and updated all 3 native extensions with SignalFx naming conventions.
* Span and trace IDs are now kept on the native side as uint64 stack which meant all code using `new SpanContext` with self-generated trace and span ids broke down (i.e. propagators), the new api to push span and trace IDs is `dd_trace_push_span_id` and `dd_trace_set_trace_id` which take a numerical string and return a numerical string.
* Since `dd_trace_push_span_id` takes a numerical string and b3 trace and span IDs are encoded in hex and decoding it to PHP integer might overflow the `PHP_INT_MAX`, I added `dd_trace_push_span_id_hex` and `dd_trace_set_trace_id_hex` which does the conversion on the native side. See https://github.com/seemk/signalfx-php-tracing/blob/dd-sync-pr/ext/vendor/hex_utils.c and https://github.com/seemk/signalfx-php-tracing/blob/dd-sync-pr/ext/php7/random.c#L104
* Improved hex conversion and validity checking: https://github.com/seemk/signalfx-php-tracing/blob/dd-sync-pr/ext/vendor/hex_utils.c#L22
* Updated propagators to the new trace/span id push API.
* Updated SignalFx environment variables for the new configuration loading (https://github.com/seemk/signalfx-php-tracing/blob/dd-sync-pr/bridge/configuration.php#L184)
* Updated native extensions with the correct SFX tags.
* Fixed `curl_setopt` hooking as with the upstream merge it no longer worked. To hook additional curl functions they need to be registered on the native side with  `ddtrace_replace_internal_function` first: https://github.com/seemk/signalfx-php-tracing/blob/dd-sync-pr/ext/php7/handlers_curl.c#L435
* `curl_setopt` hook stored its span values in `ArrayKVStore`, which worked fine for PHP <= 7, but broke down in PHP 8 as the curl handle is no longer a resource, but a class instance, however no dynamic properties can be set on this instance (so `ObjectKVStore` can't be used either). Fixed by using PHP8's `WeakMap` for temporary storage: https://github.com/seemk/signalfx-php-tracing/blob/dd-sync-pr/src/DDTrace/Integrations/Curl/CurlIntegration.php#L147-L158
* `JsonZipkinV2.php` - fixed span encoding to not rely on string replaces for nanosecond to microsecond conversions. With spans having a duration less than 1us, the replacement caused invalid JSON to be produced, dropping the whole trace on the receiver side. New version: https://github.com/seemk/signalfx-php-tracing/blob/dd-sync-pr/src/DDTrace/Encoders/JsonZipkinV2.php#L79
* Fixed null terminator being added to PHP5 span error messages: https://github.com/seemk/signalfx-php-tracing/commit/213f62eafc89502bb65fe846efc64fb8b2950d8c
* Fixed various web integrations having non-descriptive span names due to DD conventions, e.g. Symfony spans named `symfony.request` instead of the actual route name. This caused spans in the APM UI to show up as (in the case of Symfony) `GET symfony.request` with the actual useful data being hidden from users.
* Fixed PDO, Memcached, Redis, ElasticSearch, etc. spans to be reported as client spans. Not reporting them as client spans caused the APM UI not to show a database and app time breakdown, instead the DB spans were reported as app time.
* PDO integration: removed calls to `rowCount` as it's not guaranteed to have this information and might throw when it is not there (for example with Drupal).
* Added Drupal 8 and Drupal 9 integration.
* Went over regression, integration tests to change the tests to SFX conventions
* Fixed CI: added custom Docker images where necessary , they are built from the same docker files as is in the `dockerfiles` directory (https://github.com/seemk/signalfx-php-tracing/tree/dd-sync-pr/dockerfiles). For example Drupal integration tests required having `gd` extension enabled, or Composer won't run, the new images have php built with `gd` extension. Temporarily hosting the images at DockerHub.
* Increased the timeout when waiting for request-replayer responses, some of the web integration tests failed due to the PHP process taking too long to exit (might be fixed in an upstream patch that just landed: https://github.com/DataDog/dd-trace-php/commit/2f3367824ac508e8174c96251d32854041dc1c87), will be cherry-picked separately outside of this PR.
* Removed OpenTracing tracer, don't think this was relevant for our usecases.

As a followup, will publish CI builder Docker images to quay.io, but this is not a blocker for this PR.

There is one failing test remaining in CI, but this is expected as it is related to `pcntl` and recently there was a patch in the upstream regarding `pcntl` (https://github.com/DataDog/dd-trace-php/commit/2f3367824ac508e8174c96251d32854041dc1c87). The current PR is already large enough, so I'll cherry-pick the last upstream commits separately after this PR is merged.

P.S. Don't squash when merging!

### CODE REVIEW

**Comment by t2t2** [comment]
oh no

**Comment by owais** [comment]
> Removed OpenTracing tracer, don't think this was relevant for our usecases.

Can you elaborate on this please? Are we not OpenTracing complaint anymore or did we remove some additional implementation of OT tracer that was not being used? I think as long as the "SignalFx tracer" satisfies OpenTracing interface, we're good.

**Comment by owais** [comment]
@seemk Given how big  change this is, we'll need to make sure that SFX conventions like how we records errors as added in this [release](https://github.com/signalfx/signalfx-php-tracing/releases/tag/0.30.2-beta-sfx2) don't break

**Comment by rmfitzpatrick** [comment]
@seemk I don't think we're setting ourselves up for success with a PR of this size.  It's my suggestion that you please separate all the functional changes into their own PRs (drupal, incremental upstream merges, etc.).

**Comment by seemk** [comment]
> > Removed OpenTracing tracer, don't think this was relevant for our usecases.
> 
> Can you elaborate on this please? Are we not OpenTracing complaint anymore or did we remove some additional implementation of OT tracer that was not being used? I think as long as the "SignalFx tracer" satisfies OpenTracing interface, we're good.

I think in the olden days this PHP instrumentation depended on OpenTracing, but once the dependency was removed a compatibility layer was added, so someone using the instrumentation as a library could still call `OpenTracing\GlobalTracer::get()`, this was achieved by hooking the function call and returning a stub tracer with the correct interface. Not sure if we need this, I'm thinking we don't.

**Comment by seemk** [comment]
> @seemk Given how big change this is, we'll need to make sure that SFX conventions like how we records errors as added in this [release](https://github.com/signalfx/signalfx-php-tracing/releases/tag/0.30.2-beta-sfx2) don't break

Went over the tests to change `error.msg` and the like to `sfx.error.message` which should've caught the change. `sfx.error.message` is propagated from C (https://github.com/seemk/signalfx-php-tracing/blob/dd-sync-pr/ext/php7/serializer.c#L232) as well as PHP instrumentations.

**Comment by owais** [comment]
> I think in the olden days this PHP instrumentation depended on OpenTracing, but once the dependency was removed a compatibility layer was added, so someone using the instrumentation as a library could still call OpenTracing\GlobalTracer::get(), this was achieved by hooking the function call and returning a stub tracer with the correct interface. Not sure if we need this, I'm thinking we don't.

OK. I don't think we strictly need it to work but would be nice to have if it is not additional work or doesn't complicate things. Otherwise it's fine but let's bump the major version next release.

**Comment by seemk** [comment]
Closing in favor of #28

**Pull request closed without merging**
